### ISSUE TITLE
Javascript syntax error when Dokuwiki's compression of JS is active

### ISSUE THREAD

**Issue by elemental-lf** [micgro42/dokuwiki-plugin-instantpage#2]
It just took me some time to figure out that Dokuwiki's `js_compress()` function from `lib/exe/js.php` mangles insta.page's Javascript in such a way that it leads to a syntax error in Firefox. `js_compress` is only called when the corresponding config option is active. It probably has something to do with the style used by insta.page's author which leaves out all unnecessary semicolons. Maybe adding them would be a workaround until Dokuwiki is fixed.

**Comment by micgro42** [comment]
This should be resolved with the latest release and specifically commit fc2a74ba99a7c2582e31345fbd66df899fe8a620

**Comment by elemental-lf** [comment]
I can confirm that this workaround works. Thank you! 
But why pull the script from an external source now? The reference in `action/addScriptTag.php` could refer to an included version of the script avoiding the external dependency.

**Comment by micgro42** [comment]
Could you give the new version a try? This should load the script from the local server again

**Comment by elemental-lf** [comment]
I can confirm that the new version loads the script from the local server again. Thank you!
